[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pylint.FORMAT]
max-line-length=120

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
